config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :final_pics, only: [:show, :edit, :update]
  resources :locations, only: [:show, :index] do
    resources :benchmark_pics do
      resources :final_pics, only: [:new, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/benchmark_pic.rb
class BenchmarkPic < ApplicationRecord
  has_many :final_pics
  validates :user_id, presence: true
  #validates :json_overlay, presence: true
  has_one_attached :photo
  belongs_to :user
end

app/models/final_pic.rb
class FinalPic < ApplicationRecord
  belongs_to :user
  has_many :hashtags
  belongs_to :benchmark_pic, required: false
  has_one_attached :photo
  belongs_to :location
end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :final_pics
  has_many :benchmark_pics, through: :final_pics
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :final_pics
  has_many :benchmark_pics
  validates :name, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :devise_controller?
  after_action :verify_policy_scoped, only: :index, unless: :devise_controller?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
     flash[:alert] = "You are not authorized to perform this action."
     redirect_to(root_path)
  end

  #def skip_pundit?
  #  devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  #end
end

app/controllers/benchmark_pics_controller.rb
class BenchmarkPicsController < ApplicationController
  before_action :set_benchmark_pic, only: [:show, :edit, :update, :destroy]

  def index
    @benchmark_pics = policy_scope(BenchmarkPic)
  end

  def show
    @benchmark_pic = BenchmarkPic.find(params[:id])
  end

  def new
    @benchmark_pic = current_user.benchmark_pics.new
    @location = Location.find(params[:location_id])
    authorize @benchmark_pic
  end

  def create
    @benchmark_pic = current_user.benchmark_pics.new(benchmark_pic_params) #BenchmarkPic.new(benchmark_pic_params)
    @benchmark_pic.user = current_user
    @benchmark_pic.location_id = params[:location_id]
    authorize @benchmark_pic
    if @benchmark_pic.save
      redirect_to new_location_benchmark_pic_final_pic_path(params[:location_id], @benchmark_pic)
    else
      render :new
    end
  end

  def edit
    @benchmark_pic = BenchmarkPic.find(params[:id])
  end

  def update
    @benchmark_pic = BenchmarkPic.find(params[:id])
    @benchmark_pic.update(benchmark_pic_params)
    redirect_to new_location_benchmark_pic_final_pic_path
  end

  def destroy
    @benchmark_pic = BenchmarkPic.find(params[:id])
    @benchmark_pic.destroy
    redirect_to benchmark_pics_path
  end

  private
  # i added this one, not sure if we need a callback to share common setup
  def set_benchmark_pic
    @benchmark_pic = BenchmarkPic.find(params[:id])
    authorize @benchmark_pic
  end

  def benchmark_pic_params
    #params.require(:benchmark_pic).permit(:user_id, :photo)
    params.require(:benchmark_pic).permit(:photo, :location_id)
  end
end

app/controllers/final_pics_controller.rb
class FinalPicsController < ApplicationController
  before_action :set_final_pics, only: [:show, :edit, :update, :destroy]

  def index
    @final_pics = policy_scope(FinalPic)
  end

  def show
    @final_pic = FinalPic.find(params[:id])
  end

  def new
    @final_pic = FinalPic.new
    @benchmark_pic = BenchmarkPic.find(params[:benchmark_pic_id])
    authorize @final_pic
  end

  def create
    @final_pic = FinalPic.new(final_pic_params) #FinalPic.new(final_pic_params)
    @final_pic.user = current_user
    @final_pic.benchmark_pic = BenchmarkPic.find(params[:benchmark_pic_id])
    @final_pic.location = Location.second
    authorize @final_pic
    @final_pic.save
    redirect_to final_pic_path(@final_pic)
  end

  def edit
    @final_pic = FinalPic.find(params[:id])
    @final_pic.user = current_user
    @benchmark_pic = @final_pic.benchmark_pic
    authorize @final_pic
    authorize @benchmark_pic
  end

  def update
    @final_pic = FinalPic.find(params[:id])
    @benchmark_pic = @final_pic.benchmark_pic
    @final_pic.update(final_pic_params)
    redirect_to final_pic_path(@final_pic)
  end

  def destroy
    @final_pic = FinalPic.find(params[:id])
    @final_pic.destroy
    redirect_to final_pics_path
  end

  private
  # same as benchmark pics I added this one for callback
  def set_final_pics
    @final_pic = FinalPic.find(params[:id])
    authorize @final_pic
  end

  def final_pic_params
    params.require(:final_pic).permit(:benchmark_pic_id, :photo, :id)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_locations, only: [:show, :edit, :update, :destroy]

  def index
    @locations = policy_scope(Location)
    @locations = Location.all
    @markers = @locations.geocoded.map do |location|
      # if the location has pic
      {
        lat: location.latitude,
        lng: location.longitude,
        id: location.id,
        image_url: helpers.url_for(location.final_pics.last.photo)
      }
      # if the location doen't has phot add crropi logo
    end
  end

  def show
    @location = Location.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_locations
    @location = Location.find(params[:id])
    authorize @location
  end

  def location_params
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    skip_authorization
    @location = Location.second
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/benchmark_pics/_form.html.erb
<%= simple_form_for [@location, @benchmark_pic] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <img src="" alt="" class="benchmark_preview row justify-content-center" id="benchmark_preview">
  <div class="form-inputs custom-file-upload">
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'use benchmark pic', :class => 'btn btn-primary' %>
  </div>

  <div class="home_link">
    <%= link_to "home", root_path %>
  </div>
<% end %>

app/views/benchmark_pics/index.html.erb
<!--index of all benchmark pics taken goes here -->

app/views/benchmark_pics/new.html.erb
<!-- <p>
  <label for="imageFile">take your benchmark pic here:</label><br>
  <input type="file" id="imageFile" capture="user" accept="image/*;capture=camera">
</p>
 -->
<div class='benchmark-container text-center'>
  <%= render 'form', location: @location, benchmark_pic: @benchmark_pic,:item_wrapper_class => 'simple_form' %>
</div>

app/views/benchmark_pics/show.html.erb
show individual photos

<%= cl_image_tag @benchmark_pic.photo.key, height: 300, width: 400, crop: :fill %>

app/views/final_pics/edit.html.erb
<% if false %>
  <%= simple_form_for [@benchmark_pic, @final_pic] do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :photo, as: :file %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
<% end %>

<div class="photo-container">
  <video autoplay="" muted="" playsinline="" class="selfie-video">
          Video stream not available.
  </video>
  <%= cl_image_tag @benchmark_pic.photo.key, :quality=>"auto", class: 'benchmark_pic' %>
  <p class="selfie-startbutton">
    <img src="https://res.cloudinary.com/cyee3012/image/upload/v1615462684/croppi-shutter_zao68k.svg" alt="shutter">
  </p>
</div>

app/views/final_pics/index.html.erb
Index of all the final pics

app/views/final_pics/new.html.erb
<!--Create a new final pic here-->
<% if false %>
  <%= simple_form_for [@benchmark_pic, @final_pic] do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :photo, as: :file %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
<% end %>

<div class="photo-container">
  <video autoplay="" muted="" playsinline="" class="selfie-video">
          Video stream not available.
  </video>
  <%= cl_image_tag @benchmark_pic.photo.key, :quality=>"auto", class: 'benchmark_pic' %>
  <p class="selfie-startbutton">
    <img src="https://res.cloudinary.com/cyee3012/image/upload/v1615462684/croppi-shutter_zao68k.svg" alt="shutter">
  </p>
</div>

app/views/final_pics/show.html.erb
<div class='final_pic-container'>
  <div class='column'>
    <%= cl_image_tag @final_pic.photo.key %>
    <button type="button" class="btn btn-primary"><%= link_to "retake?", edit_final_pic_path(@final_pic) %></button>
    <div class='pad'>
      <%= social_share_button_tag('share') %>
      <br>
    </div>
    <!-- <div class="icon-row">

    </div> -->
    <div class="home_link">
      <%= link_to "home", root_path %>
    </div>
  </div>
</div>

      <!-- <div class="facebook-share-button" data="facebook"></div>
      <div class="twitter-share-button" data="twitter"></div>
      <div class="instagram-share-button" data="instagram"></div>
      <div class="tumblr-share-button" data="tumblr"></div>
      <div class="line-share-button" data="line"></div> -->

app/views/layouts/application.html.erb
<%= stylesheet_pack_tag 'application' %>
<!DOCTYPE html>
<html>
  <head>
    <title>Croppi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'shared/ios_pwa_links' %>
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <script type='text/javascript' src='https://platform-api.sharethis.com/js/sharethis.js#property=6042e4ad9c00ae0011d4179d&product=sop' async='async'></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=#{property?._id}&product=custom-share-buttons"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <%= render 'shared/flashes' %>
  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/locations/index.html.erb
<div id="map"
     style=";position: absolute; top: 0; bottom: 0; width: 100%;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/locations/show.html.erb
<%= render 'shared/navbar' %>

<div class="location-show-container">

  <div class="address">
    <%= @location.address %>
  </div>

  <div class="photo-banner">
  <%= cl_image_tag @location.final_pics.first.photo.key, :quality=>"auto", :gravity=>"auto", :crop=>"fill" %>
  </div>

  <div class="photo-cards">
    <% @location.final_pics.each do |final_pic| %>
      <% if final_pic.photo.attached? %>
        <div id ="myImg" class="photo-card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path final_pic.photo.key, :quality=>"auto" %>')" data-bigger-src="<%= cl_image_path final_pic.photo.key, :quality=>"auto" %>"> </div>
      <% else %>
        <div id ="myImg" class="photo-card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://res.cloudinary.com/dlzehsqej/image/upload/v1614934364/Screenshot_2021-03-05_at_17.48.27_l9asdj.png')"></div>
      <% end %>
    <% end %>
  </div>

  <div id="myModal" class="modal">
  <span class="close">&times;</span>
  <img id="modal-img" class="modal-content"  src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQS2ol73JZj6-IqypxPZXYS3rRiPwKteoD8vezk9QsRdkjt3jEn&usqp=CAU">





  <div id="caption"></div>
</div>

  <div class="icons-row">
    <div class="icons">
      <%= link_to image_tag("https://res.cloudinary.com/dlzehsqej/image/upload/v1614851879/map_yhtlqb.png"), locations_path %>
    </div>
    <div class="icons">
      <%= link_to image_tag("https://res.cloudinary.com/cyee3012/image/upload/v1614408344/camera_mlxbk0.png"), new_location_benchmark_pic_path(@location) %>
    </div>
    <div class="icons">
        <%= link_to image_tag("https://res.cloudinary.com/dlzehsqej/image/upload/v1614931296/position_coedmt.png"), "http://www.google.com/maps/place/#{@location.latitude},#{@location.longitude}" %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'shared/navbar' %>
<div class="banner-container">
  <div class="container-fluid">
    <div class="row">

      <div class="banner">
        <h2>say no to crappy photos
          <br>use croppi
        </h2>
        <button type="button" class="btn btn-primary"><%= link_to "shoot", new_location_benchmark_pic_path(@location) %>
      </button>
      <br>
        <div class="map_link">
          <%= link_to "checkout photos nearby", locations_path %>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- <div class='container'> -->

  <div class="pl-1">
    <img src="https://res.cloudinary.com/cyee3012/image/upload/v1615463129/placeholder_jfmkgr.svg" alt="shutter">
    Bali </div>

    <div class="cards scrolling-wrapper-flexbox">
      <div id ="myImg" class="card" style="background-image: url(https://res.cloudinary.com/dlzehsqej/image/upload/q_auto/v1614996624/image_muk20j.jpg)" data-bigger-src="https://res.cloudinary.com/dlzehsqej/image/upload/v1614996624/image_muk20j.jpg"> </div>
      <div id="myImg" class="card" style="background-image: url(https://res.cloudinary.com/dlzehsqej/image/upload/q_auto/v1614996632/IMG_8666-1_ambt1d.jpg)" data-bigger-src="https://res.cloudinary.com/dlzehsqej/image/upload/q_auto/v1614996632/IMG_8666-1_ambt1d.jpg"> </div>
      <div id ="myImg" class="card" style="background-image: url(https://res.cloudinary.com/dlzehsqej/image/upload/q_auto/v1614996640/news-78_ncucsa.jpg)" data-bigger-src="https://res.cloudinary.com/dlzehsqej/image/upload/v1614996640/news-78_ncucsa.jpg"> </div>
      <div id ="myImg" class="card" style="background-image: url(https://res.cloudinary.com/dlzehsqej/image/upload/v1616801218/Bali-swings-elya-front_n9amt4.jpg)" data-bigger-src="https://res.cloudinary.com/dlzehsqej/image/upload/v1616801218/Bali-swings-elya-front_n9amt4.jpg"> </div>
    </div>

  <div class='pl-1'>
    <img src="https://res.cloudinary.com/cyee3012/image/upload/v1615463129/placeholder_jfmkgr.svg" alt="shutter">
    United Kingdom </div>
    <div class="cards scrolling-wrapper-flexbox">
       <div id ="myImg" class="card" style="background-image: url(https://res.cloudinary.com/dlzehsqej/image/upload/q_auto/v1614997234/UK-1_pa5iot.jpg)" data-bigger-src="https://res.cloudinary.com/dlzehsqej/image/upload/v1614997234/UK-1_pa5iot.jpg"> </div>
       <div id ="myImg" class="card" style="background-image: url(https://res.cloudinary.com/dlzehsqej/image/upload/q_auto/v1614997242/UK-2_vuftp7.jpg)" data-bigger-src="https://res.cloudinary.com/dlzehsqej/image/upload/v1614997242/UK-2_vuftp7.jpg"> </div>
       <div id ="myImg" class="card" style="background-image: url(https://res.cloudinary.com/dlzehsqej/image/upload/q_auto/v1614997250/UK-4_ratwmq.jpg)" data-bigger-src="https://res.cloudinary.com/dlzehsqej/image/upload/v1614997250/UK-4_ratwmq.jpg"> </div>
       <div id ="myImg" class="card" style="background-image: url(https://res.cloudinary.com/dlzehsqej/image/upload/v1616801348/20180720110212_643825018_10339_0_bnfihw.jpg)" data-bigger-src="https://res.cloudinary.com/dlzehsqej/image/upload/v1616801348/20180720110212_643825018_10339_0_bnfihw.jpg"> </div>
    </div>

  <div class='pl-1'>
    <img src="https://res.cloudinary.com/cyee3012/image/upload/v1615463129/placeholder_jfmkgr.svg" alt="shutter">
    Los Angeles </div>
    <div class="cards scrolling-wrapper-flexbox">
      <div id ="myImg" class="card" style="background-image: url(https://res.cloudinary.com/dlzehsqej/image/upload/q_auto/v1614997525/LA-1_wg1kr7.jpg)" data-bigger-src="https://res.cloudinary.com/dlzehsqej/image/upload/v1614997525/LA-1_wg1kr7.jpg"> </div>
       <div id ="myImg" class="card" style="background-image: url(https://res.cloudinary.com/dlzehsqej/image/upload/q_auto/v1614997534/LA-2_grbrhb.jpg)" data-bigger-src="https://res.cloudinary.com/dlzehsqej/image/upload/v1614997534/LA-2_grbrhb.jpg"> </div>
       <div id ="myImg" class="card" style="background-image: url(https://res.cloudinary.com/dlzehsqej/image/upload/q_auto/v1614997539/LA-3_o2g4vu.jpg)" data-bigger-src="https://res.cloudinary.com/dlzehsqej/image/upload/v1614997539/LA-3_o2g4vu.jpg"> </div>
       <div id ="myImg" class="card" style="background-image: url(https://res.cloudinary.com/dlzehsqej/image/upload/v1616801585/Harbor-Freeway-Los-Angeles_pwf7op.jpg)" data-bigger-src="https://res.cloudinary.com/dlzehsqej/image/upload/v1616801585/Harbor-Freeway-Los-Angeles_pwf7op.jpg"> </div>
    </div>

<!-- </div> -->
                                                    <!-- The Modal -->

<div id="myModal" class="modal">
  <span class="close">&times;</span>
  <img id="modal-img" class="modal-content"  src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQS2ol73JZj6-IqypxPZXYS3rRiPwKteoD8vezk9QsRdkjt3jEn&usqp=CAU">


  <div id="caption"></div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "croppi-logo.svg", alt: "logo" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>